# Generated by Django 4.0.6 on 2022-09-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='Price',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='price',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='salary',
            field=models.CharField(max_length=25),
        ),
    ]
